### ISSUE TITLE
Train error

### ISSUE THREAD

**Issue by GithubAccountTo** [damNull/LAGCN#6]
when I run "python main.py --config configs/ntu60-xsub/joint.yaml --work-dir work_dir/ntu60/csub/lagcn_joint --device 0", I get an error
<img width="1218" alt="image" src="https://github.com/damNull/LAGCN/assets/81542169/561426af-ca70-4f00-aa1b-b6b3b1843df5">
<img width="804" alt="image" src="https://github.com/damNull/LAGCN/assets/81542169/03280755-419e-4f90-885f-efce18a04334">
so, I changed the code 
<img width="973" alt="image" src="https://github.com/damNull/LAGCN/assets/81542169/132c7167-e0b7-4f39-85e5-9971ca4427f0">
to
<img width="931" alt="image" src="https://github.com/damNull/LAGCN/assets/81542169/6dedb45f-7bf5-44e1-b410-598e5c236fbe">
Next I trained the network, but I modified the network structure, I don't know what the bad effects are

**Comment by damNull** [comment]
Set "loop_times" to 0 is to deactivate the MHAGC. According to the article, the performance will drop. For the shape mismatch in lagcn.py:185, you can simply print the shape of A to check the problem. I guess there's a problem with the data preparation. The code is running well in our environment.

**Comment by GithubAccountTo** [comment]
@damNull , thank you for your reply. Here are the details of my environment that may be different from yours, python==3.6, cuda version ==11.3, mkl-random==1.0.1.1, mkl-fft==1.0.6, don't install mkl-service. And can you provide the data you processed for me to test.

**Comment by damNull** [comment]
The preprocessed data of NTU 60/120 is too large. You can check the input tensor shape to fix the problem. The shape of the input tensor is N (batch_size), C (channels), T (frames), V (num_joints), M (num_person). Or you can follow the data preprocessing code in https://github.com/Uason-Chen/CTR-GCN.

**Comment by GithubAccountTo** [comment]
I add 
 `A_power = A_power.repeat(A.shape[0], A.shape[1], 1, 1)`
after lagcn.py:183. It seems normal, but I don't konw why can't it broadcast automatically

**Comment by damNull** [comment]
In my environment, the code is no problem. According to your issue (#7), the MHA-GC is working normally.
