### ISSUE TITLE
Is the test result normal

### ISSUE THREAD

**Issue by GithubAccountTo** [damNull/LAGCN#7]
I test the pre_trained model ntu60/xsub/b.pt loaded from https://drive.google.com/file/d/1Yz86jwjj_EAeqf8-KVBPsM9lVQWz-mCM/view?usp=drive_link.  The dataset is ntu-60 and the results are shown in the figure below
<img width="849" alt="image" src="https://github.com/damNull/LAGCN/assets/81542169/c3f5666a-3a57-4928-82b4-1d0048232a6e">
The indicators look low

**Comment by damNull** [comment]
According to your issue (#6), the MHA-GC is deactivated, so the performance does not match.

**Comment by GithubAccountTo** [comment]
@damNull I activate MHA-GC. Then I test ntu60 x-sub,  but the best top1 acc of download models is 90.90%, which don't match 93.5% from the paper.

**Comment by damNull** [comment]
The 93.5% result is the ensemble of **6 streams**. The best single-stream model is 90.90%. To obtain the ensemble result, you can use the script `ensemble_6s.py` in repo.

**Comment by GithubAccountTo** [comment]
I trained the model using the ntu60 x-sub and tested epoch1_test_score. pkls which were generated during training. The Top1 acc was 93.3159%, and the top5 acc was 99.0053%. The results of online model testing are as follows: the top1 acc is 93.4494%, and the top5 acc is 98.9507%. The difference could be due to random seeds, right?

**Comment by damNull** [comment]
The environment difference could affect the training result (e.g. CUDA version, CPU, GPU ...).
