### ISSUE TITLE
Do you have any tutorial how to fine-tuning with my own data??

### ISSUE THREAD

**Issue by hotelbread** [damNull/LAGCN#9]
Hi. I am interested in your work. Thank you for your efforts.
I am Taewon, and I am looking for a great skeleton-based action recognition model. I am somewhat of a beginner in this field.
So, I lack knowledge on how to customize what I want to do.
Actually, I have my own video and skeleton data. (I am able to handle the skeleton data that I have; I just don't know what I need)
If you can advise me, it would be really helpful and I would greatly appreciate it.

Thanks.
Regards,
Taewon.

**Comment by damNull** [comment]
You only need to make a "npz" format like ntu/ntu120.
The npz file contains keys:
`['x_train', 'y_train', 'cnt_train', 'x_test', 'y_test', 'cnt_test']`
x, y, cnt denote data label and frame counts respectively.

The shape of x is [num_samples, max_frames, 150],  and x is zero-padded. 150 -> 3D coordinate of 25 points.
The shape of y is [num_samples, num_classes]. The format of y is the stack one-hot vector.
The shape of cnt is  [num_samples,].

**Comment by hotelbread** [comment]
Based on NTU60_CS.npz, there are only x_train, y_train, x_test, and y_test, and I can't find any values related to 'cnt'. What could be the issue?
![image](https://github.com/damNull/LAGCN/assets/91708227/d4470cdb-bedf-4486-ba55-ae6e60bfdb25)

**Comment by damNull** [comment]
Without "cnt" key is also ok.

**Comment by hotelbread** [comment]
Thank you for your fast answer! Now I understood of Y. But still I don't get it about X. 
      The shape of x is [num_samples, max_frames, 150], and x is zero-padded. 150 -> 3D coordinate of 25 points.
num_samples : number of video clips
max_frames : The number of frames in the longest video clip
(If we assume max_frames is 300, and a video clip has 130 frames, should the remaining 170 frames be filled with zeros?)
150 : It is the most hardest to understand. Each of the 25 joint points has 3D coordinates [x1, y1, z1, x2, y2, z2, ... x25, y25, z25], resulting in 75 coordinates. Additionally, if we include the 2D coordinates (in percentages) based on the RGB video, it would be structured as:
[x1, y1, z1, x2, y2, z2, ... x25, y25, z25, x1(2d), y1(2d), x2(2d), y2(2d), ..., x25(2d), y25(2d)].
This results in 125 coordinates. However, there are still 25 coordinates missing. What should be added to fill these 25 coordinates? Also, if my understanding of the data structure is incorrect, please correct it.

Thank you for your kind assistance.
Additionally, do you have any inference code to check if the training was successful?

**Comment by damNull** [comment]
Sorry, I forgot the key points are from 2 people. (25 x 3 x 2 = 150 )

**Comment by hotelbread** [comment]
Thank you. I feel like I'm starting to grasp the overall structure of your model a bit better.

In the current situation, there seems to be no code available to analyze and visualize arbitrary videos even after fine-tuning the model. However, using external libraries or tools to extract 3D coordinates of individuals from videos, such as mediapipe, and then running them through a recognizer at regular intervals for analysis and visualization, could be one approach. What do you think?

**Comment by damNull** [comment]
That should be a solution.

**Comment by hotelbread** [comment]
Hello author, I am currently facing some problems with starting the fine-tuning process.
To start fine-tuning using the pretrained weights you've been provided, is it simply put this '--weight your_pretrained_weights'?? Then, since I am starting my own class, the number of classes will naturally change. Is it correct to only adjust the number of classes in the yaml file? 
I'll check it out first and if I have any more questions, I'll leave a comment on this post again.
thank you!!!

**Comment by damNull** [comment]
You need to reset the parameter of the FC layer manually.

**Comment by hotelbread** [comment]
---

As you mentioned, I'm trying to manually modify the `fc_layer`, but the structure is not clear to me...

After changing `num_class` to 26, the error occurs as follows:

```
RuntimeError: shape '[100, 2, 26]' is invalid for input of size 12000
```

To understand the tensor sizes, I printed them, and it appears that the problem is here:

```
Reshaped aux_x shape: torch.Size([200, 60])
Check for self.examplar: torch.Size([60, 25, 25])
Check for self.num_class: 26
```

It seems something is going wrong in this part. Could you help me out?

**Comment by damNull** [comment]
You need to regenerate the CPR Graph matrix according to the classes in your dataset. The relevant code will be released after the article is accepted. Please wait patiently.
